---
- include: "{{ project_deploy_initialize_before }}"
  tags: deploy-initialize-before
  when: project_deploy_initialize_before is defined

- name: Initialize
  deploy_helper:
    path: "{{ project_deploy_root }}"
    state: present

- include: "{{ project_deploy_initialize_before }}"
  tags: deploy-initialize-after
  when: project_deploy_initialize_before is defined
