---
- include: "{{ project_deploy_share_before }}"
  tags: deploy-share-before
  when: project_deploy_share_before is defined

- name: Ensure shared sources are present
  file:
    path: "{{ deploy_helper.shared_path }}/{{ item.src }}"
    state: "{{ item.type | default('directory') }}"
    mode: "{{ item.mode | default('0755') }}"
  with_items: "{{ project_deploy_shared_children }}"

- name: Ensure shared paths are absent
  file:
    path: "{{ deploy_helper.new_release_path }}/{{ item.path }}"
    state: absent
  with_items: "{{ project_deploy_shared_children }}"

- name: Create shared symlinks
  file:
    path: "{{ deploy_helper.new_release_path }}/{{ item.path }}"
    src: "{{ deploy_helper.shared_path }}/{{ item.src }}"
    state: link
  with_items: "{{ project_deploy_shared_children }}"

- include: "{{ project_deploy_share_after }}"
  tags: deploy-share-after
  when: project_deploy_share_after is defined
